import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import * as React from "react";
import "./globals.css";
import SessionAuthProvider from "../context/SessionAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
    <body>
      <Providers>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <SessionAuthProvider>{children}</SessionAuthProvider>
      </main>
      </Providers>
    </body>
  </html>
  );
}